name: Azure Resource Creation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-resource:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Create a Resource Group and Storage Account using Azure CLI
    - name: Create Azure Resources
      run: |
        # Set variables
        RESOURCE_GROUP="test-action-created-1"
        LOCATION="germanywestcentral"

        echo "Creating resource group: $RESOURCE_GROUP in $LOCATION"
        resExist=$(az group exists --name $RESOURCE_GROUP)
        
        if [ "$resExist" = true ]; then
          echo "resource group $RESOURCE_GROUP already exists"
        else
          echo "Creating resource group: $RESOURCE_GROUP in $LOCATION"
          az group create --name $RESOURCE_GROUP --location $LOCATION
        fi
      shell: bash

    - name: Run Script with Secrets
      shell: pwsh
      run: |
        $scriptPath = "${{ vars.REG_SCRIPT_PATH }}"
        chmod +x $scriptPath
        pwsh ${{ vars.REG_SCRIPT_PATH }}
