name: Build Project
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  run: |
    echo 'Build, Test and push to artifact'
    echo "SOLUTION_PATH - ${{ vars.SOLUTION_PATH }}"
    echo "OUTPUT_FILENAME - ${{ vars.OUTPUT_FILENAME }}"
    echo "TEST_PATH - ${{ vars.TEST_PATH }}"
    
jobs:
  build:
    uses: SankumSan/github-actions/.github/workflows/build-dotnet-workflow.yml@main
    with:
      SOLUTION_PATH: ${{ vars.SOLUTION_PATH }}
      OUTPUT_FILENAME: ${{ vars.OUTPUT_FILENAME }}
      TEST_PATH: ${{ vars.TEST_PATH }}
