name: Build Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: SankumSan/github-actions/.github/workflows/build-dotnet-workflow.yml@main
    with:
      SOLUTION_PATH: ${{ vars.SOLUTION_PATH }}
      OUTPUT_FILENAME: ${{ vars.OUTPUT_FILENAME }}
      TEST_PATH: ${{ vars.TEST_PATH }}

  # Optionally, you can add a job to log variables before running the build workflow
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs and Secrets
        run: |
          echo "Azure Registry Username: ${{ secrets.AZURE_REGISTRY_USERNAME }}"  # This will be masked in the logs
