name: Build and Deploy RabbitMQ to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  deploy-rabbitmq:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        echo "$docker file path = {{ vars.DOCKER_RMQ }}"
        docker build -f ${{ vars.DOCKER_RMQ }} -t ${{ secrets.DOCKER_USERNAME }}/rabbitmq:3-management .
        docker push ${{ secrets.DOCKER_USERNAME }}/rabbitmq:3-management
        echo "build and push to docker hub done...!"

    - name: Deploy to Azure Container Apps with Volumes
      run: |
        az containerapp update \
          --name rabbitmq \
          --resource-group acr_actions \
          --image ${{ secrets.DOCKER_USERNAME }}/rabbitmq:3-management \
          --cpu 0.5 \
          --memory 1.0Gi \
          --min-replicas 1 \
          --max-replicas 3 \
          --revision-suffix rabbitmq-volumes \
          --secret-volume-mount \
            /data=/mnt/data-storage \
            /logs=/mnt/log-storage

    - name: Configure RabbitMQ Persistent Storage
      run: |
        echo "Add storage for rabbitmq-data"
        az containerapp storage add \
          --name rabbitmq \
          --resource-group acr_actions \
          --storage-name data-storage \
          --type AzureFile \
          --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
          --share-name rabbitmq-data
        
        echo "Add storage for rabbitmq-logs"
        az containerapp storage add \
          --name rabbitmq \
          --resource-group acr_actions \
          --storage-name log-storage \
          --type AzureFile \
          --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
          --share-name rabbitmq-logs
