name: Build and Deploy RabbitMQ to Azure Container Apps

on:
  push:
    branches:
      - main
env:
  dockerrepo_name: sanrabmq
  
jobs:
  deploy-rabbitmq:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        echo "$docker file path = {{ vars.DOCKER_RMQ }}"
        # docker build -f Dockerfile -t rabbitmq:3-management .
        # docker tag your_image_name:tag username/rabbitmq-public:tag
        #docker build -f ${{ vars.DOCKER_RMQ }} -t ${{ secrets.DOCKER_USERNAME }}/rabbitmq:3-management .
        docker build -f ${{ vars.DOCKER_RMQ }} -t rabbitmq:3-management .
        docker tag rabbitmq:3-management ${{ secrets.DOCKER_USERNAME }}/sanrabmq:latest
        # docker push username/rabbitmq-public:tag
        docker push ${{ secrets.DOCKER_USERNAME }}/sanrabmq:latest
        echo "build and push to docker hub done...!"
