name: Build Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: SankumSan/github-actions/.github/workflows/build-dotnet-workflow.yml@main
    with:
      SOLUTION_PATH: ${{ vars.SOLUTION_PATH }}
      OUTPUT_FILENAME: ${{ vars.OUTPUT_FILENAME }}
      TEST_PATH: ${{ vars.TEST_PATH }}

  # Optionally, you can add a job to log variables before running the build workflow
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs and Secrets
        run: |
          echo "Azure Registry Username: ${{ secrets.AZURE_REGISTRY_USERNAME }}"
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the Repository, needed because to access script file
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Make the Shell Script Executable
      - name: Set Script Permissions
        run: chmod +x ${{vars.REG_SCRIPT_PATH}}

      # 3. Run the Shell Script
      - name: Execute Shell Script
        run: ${{vars.REG_SCRIPT_PATH}}
        
      - name: Outputs
        run: |
          echo "Azure Container Registry created from script at : ${{vars.REG_SCRIPT_PATH}}"
