name: Container App Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-resource:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # https://github.com/marketplace/actions/azure-container-apps-build-and-deploy
    - name: Build and deploy to Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        resourceGroup: acr_actions  #Azure resource group name
        acrName: mydockerimagessancr7 # Azure Container Registry name
        containerAppName: cont-app-ex-1 # Azure Container app name
        imageToBuild: mydockerimagessancr7.azurecr.io/test-web-app-net8:${{ github.run_number }} #cretes new image with this name
        containerAppEnvironment: my-test-virtual-env

    - name: END
      run: |
        # echo "GWS = ${{ github.workspace }}"
        echo "STEPS finished...!"